// Compatibility re-exports: the creative model lives in the pure engine layer.
export {
  campaignCta,
  campaignTypes,
  compositionChoices,
  defaultRequired,
  effectivePriorities,
  goalPriorities,
  hasContent,
  goals,
  offerLimit,
  sample,
  spacings,
  textKeys,
  toSpec,
  validateCreative,
  type CampaignType,
  type CompositionChoice,
  type CreativeData as Creative,
  type CreativeKey,
  type Spacing,
  type TextKey,
} from "../engine/creativeModel";
