import type { Creative, Surface } from "../engine/types";
export const sample: Creative = {
  brand: "VOXORA",
  headline: "Sound without limits.",
  price: "From $129",
  cta: "Shop now",
  image: "/headphones.jpg",
  background: "#f5f0e7",
  foreground: "#262d24",
  accent: "#c74620",
  focalX: 50,
  focalY: 50,
  priorities: { brand: 30, headline: 100, image: 70, price: 50, cta: 100 },
};
const defaults = { safe: 24, minFont: 14, minTarget: 44, minContrast: 4.5 };
export const surfaces: Surface[] = [
  {
    ...defaults,
    id: "portrait",
    name: "Mobile portrait",
    width: 360,
    height: 640,
    category: "Core surfaces",
  },
  {
    ...defaults,
    id: "landscape",
    name: "Mobile landscape",
    width: 640,
    height: 360,
    category: "Core surfaces",
  },
  {
    ...defaults,
    id: "broadcast",
    name: "Broadcast lower-third",
    width: 1200,
    height: 200,
    safe: 16,
    category: "Core surfaces",
  },
  {
    ...defaults,
    id: "kiosk",
    name: "Retail kiosk",
    width: 600,
    height: 600,
    safe: 32,
    category: "Core surfaces",
  },
  {
    ...defaults,
    id: "tight",
    name: "Constrained banner",
    width: 240,
    height: 80,
    safe: 8,
    minFont: 12,
    minTarget: 32,
    category: "Stress tests",
  },
  {
    ...defaults,
    id: "google-rectangle",
    name: "Google · Medium rectangle",
    width: 300,
    height: 250,
    safe: 12,
    minFont: 12,
    category: "Google Display",
    source: "https://support.google.com/google-ads/answer/7031480",
    note: "Composed image size preview. File limits and campaign policies require separate review.",
  },
  {
    ...defaults,
    id: "google-leaderboard",
    name: "Google · Leaderboard",
    width: 728,
    height: 90,
    safe: 8,
    minFont: 12,
    minTarget: 32,
    category: "Google Display",
    source: "https://support.google.com/google-ads/answer/7031480",
    note: "Composed image size preview, not a guarantee of platform approval.",
  },
  {
    ...defaults,
    id: "taboola-concept",
    name: "Taboola · Native concept",
    width: 1200,
    height: 675,
    safe: 32,
    category: "Native advertising",
    source:
      "https://developers.taboola.com/backstage-api/docs/item-thumbnail_url",
    note: "Concept only: Taboola assembles image, title, and branding separately. This composed canvas is not the actual native ad or a submission-ready thumbnail. Dimensions follow its preferred 16:9 image ratio; submit assets separately.",
  },
  {
    ...defaults,
    id: "custom",
    name: "Custom surface",
    width: 480,
    height: 480,
    category: "Your dimensions",
  },
];
